# -*- coding: utf-8 -*-
"""Natural Language Processing (NLP).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19KtDmuK_eviBnPI8Sl7eeDXF4tJ0LSno
"""

!pip install nltk spacy
!python -m spacy download en_core_web_sm

import nltk
from nltk.corpus import movie_reviews
import spacy

# Download the movie_reviews dataset
nltk.download('movie_reviews')

# Load spaCy's English model
nlp = spacy.load('en_core_web_sm')

def preprocess_and_tokenize(text):


    # Process the text with spaCy
    doc = nlp(text)

    # Preprocess and tokenize
    tokens = [token.text for token in doc if not token.is_punct and not token.is_stop and not token.is_space]

    return tokens

#Loading the movie_reviews dataset and preprocessing
review_text = movie_reviews.raw(movie_reviews.fileids()[0])

# Preprocess and tokenize the review text
tokens = preprocess_and_tokenize(review_text)

print(f"Original Text: {review_text[:500]}")
print("\nPreprocessed Tokens:")
print(tokens)